name: tfgrid_sdk_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: ">=3.0.0 <5.0.0"
  test: ^1.24.0

dependencies:
  coverage: ^1.7.1
  melos: ">=4.1.0 <7.0.0"
  signer: 
    git:
      url: https://github.com/codescalers/tfgrid-sdk-dart.git
      ref: main
      path: packages/signer
    version: any
  substrate_bip39: ^0.4.0
  tfchain_client:
    path: ./packages/tfchain_client 

