name: tfchain_client
description: A sample command-line application.
version: 0.1.0

environment:
  sdk: ^3.2.3

dependencies:
  polkadart: ^0.4.3
  polkadart_keyring: ^0.4.3
  substrate_bip39: ^0.4.0
  polkadart_cli: ^0.4.2
  hex: ^0.2.0
  bip39: ^1.0.6
  moment_dart: ^2.0.2
  signer: 
    git:
      url: https://github.com/codescalers/tfgrid-sdk-dart.git
      ref: main
      path: packages/signer
  hashlib: ^1.13.1
  substrate_metadata: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  coverage: ^1.7.1

polkadart:
  output_dir: lib/generated
  chains:
    dev: wss://tfchain.dev.grid.tf/ws
    # qa: wss://tfchain.qa.grid.tf/ws
    # test: wss://tfchain.test.grid.tf/ws
    # main: wss://tfchain.grid.tf/ws
