name: signer
description: A signer to sign and verify raw data
version: 1.0.0

environment:
  sdk: ^3.2.0

dependencies:
  hex: ^0.2.0
  polkadart_keyring: ^0.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  coverage: ^1.7.1

scripts:
  test: --coverage=coverage
